import os
import re
import json
import subprocess
import sys

def find_imports_in_notebooks(root_dir="."):
    """
    Scan all .ipynb files in the specified directory and extract import statements.
    
    Args:
        root_dir (str): Root directory to scan for .ipynb files
        
    Returns:
        list: Sorted list of unique import statements
    """
    # Regular expression to match import statements
    import_pattern = re.compile(
        r'^(?:import|from)\s+[\w\.]+',
        re.MULTILINE
    )
    
    all_imports = set()
    
    print(f"Scanning directory: {os.path.abspath(root_dir)}")
    
    for root, dirs, files in os.walk(root_dir):
        # Ignore common unnecessary directories
        dirs[:] = [d for d in dirs if d not in ['.venv', 'venv', '.git', '__pycache__', '.ipynb_checkpoints']]
        
        for file in files:
            if file.endswith(".ipynb"):
                file_path = os.path.join(root, file)
                
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        notebook = json.load(f)
                    
                    # Traverse all code cells in the notebook
                    for cell in notebook.get('cells', []):
                        if cell.get('cell_type') == 'code':
                            code = ''.join(cell.get('source', []))
                            matches = import_pattern.findall(code)
                            for match in matches:
                                all_imports.add(match.strip())
                                
                except Exception as e:
                    print(f"    [Warning] Error reading file {file_path}: {e}")
    
    return sorted(list(all_imports))

def write_imports_to_file(imports_list, output_file="collected_imports.py"):
    """
    Write the collected import statements to a Python file.
    
    Args:
        imports_list (list): List of import statements
        output_file (str): Output file path
    """
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("#!/usr/bin/env python3\n")
        f.write("# -*- coding: utf-8 -*-\n")
        f.write("\"\"\"\n")
        f.write("This file contains all unique import statements collected from Jupyter Notebooks.\n")
        f.write("Generated by find_imports.py\n")
        f.write("\"\"\"\n\n")
        
        for imp in imports_list:
            # Complete from ... import statements for direct execution
            if imp.startswith('from') and 'import' not in imp:
                f.write(f"{imp} import *\n")
            else:
                f.write(f"{imp}\n")
    
    print(f"\nSuccessfully wrote {len(imports_list)} unique import statements to {output_file}")

def generate_requirements_txt():
    """
    Generate requirements.txt using pipreqs
    """
    try:
        # Run pipreqs to generate requirements.txt
        result = subprocess.run(
            ["pipreqs", ".", "--force"],
            check=True,
            capture_output=True,
            text=True
        )
        print("\nrequirements.txt generated successfully using pipreqs")
        return True
    except subprocess.CalledProcessError as e:
        print(f"\nError generating requirements.txt: {e}")
        print(f"pipreqs output: {e.stderr}")
        return False
    except FileNotFoundError:
        print("\nError: pipreqs not found. Please install it first with: pip install pipreqs")
        return False

if __name__ == "__main__":
    # Step 1: Scan all .ipynb files and extract import statements
    collected_imports = find_imports_in_notebooks()
    
    # Step 2: Write imports to collected_imports.py
    if collected_imports:
        write_imports_to_file(collected_imports)
        
        # Step 3: Generate requirements.txt using pipreqs
        generate_requirements_txt()
    else:
        print("\nNo import statements found.")